min_count_bigrams : 15
min_count_trigrams : 15
tdf_no_below : 6
tdf_no_above : 0.75
docvec_window : 10
docvec_min_count : 7
docvec_sample : 0.001
docvec_alpha : 0.1
docvec_epochs : 40
tdf_num_topics : 400
docvec_vector_size : 400
