root_dir  : /media/diego/QData/techarticles/
lsi_models_dir_base : models/lsi/lsi_
lsi_models_dir_link : models/lsi/15_lsi_model
doc2vec_models_dir_base : models/doc2vec/doc2vec__
doc2vec_models_dir_link : models/doc2vec/15_doc2vec_model
doc2vec_models_file_link : models/doc2vec/doc2vec_model/doc2vec
key_file           : /media/diego/QData/techarticles/keys/db_coords.yml
pickle_dir          : pickle/
text_pickle_file     : pickle/texts.p
bigrams_pickle_file     : pickle/bigrams.p
trigrams_pickle_file     : pickle/trigrams.p
phrases_model_dir_base    : models/phrases/phrases__
phrases_model_dir_link     : models/phrases/15_phrases_model
xgboost_model_file        : models/xgboost/xgboost_model
xgboost_classifier_file        : models/xgboost/xgboost_classifier
version                   : 15
threshold         : 0.9
go_back  : 30
tf_threshold : 0.59
doc_threshold : 0.31
tok_action : append


