root_dir  : /media/diego/QData/techarticles/
lsi_models_dir_base : models/lsi/lsi_
lsi_models_dir_link : models/lsi/15_lsi_model
doc2vec_models_dir_base : models/doc2vec/doc2vec__
doc2vec_models_dir_link : models/doc2vec/15_doc2vec_model
doc2vec_models_file_link : models/doc2vec/doc2vec_model/doc2vec
key_file           : /media/diego/QData/techarticles/keys/db_coords.yml
pickle_dir          : pickle/
text_pickle_file     : pickle/texts.p
bigrams_pickle_file     : pickle/bigrams.p
trigrams_pickle_file     : pickle/trigrams.p
phrases_model_dir_base    : models/phrases/phrases__
phrases_model_dir_link     : models/phrases/15_phrases_model
xgboost_model_dir        : models/xgboost/
xgboost_model_file        : models/xgboost/xgboost_model
xgboost_classifier_file        : models/xgboost/xgboost_classifier
version                   : 15
threshold         : 0.65
go_back  : 20
score_go_back : 20
tf_threshold : 0.60
doc_threshold : 0.36
tok_action : append
version_dir : /media/diego/QData/techarticles/version/
list_limit : 10000
group_limit : 30000

max_skipped : 250
rtf_model_dir        : models/rtf/
rtf_model_file        : models/rtf/rtf_model
rtf_classifier_file        : models/rtf/rtf_classifier
sgd_model_dir        : models/sgd/
sgd_model_file        : models/sgd/sgd_model
sgd_classifier_file        : models/sgd/sgd_classifier