root_dir  : /media/diego/QData/techarticles/
lsi_models_dir_base : models/lsi/lsi_
lsi_models_dir_link : models/lsi/lsi_model
doc2vec_models_dir_base : models/doc2vec/doc2vec__
doc2vec_models_dir_link : models/doc2vec/doc2vec_model
doc2vec_models_file_link : models/doc2vec/doc2vec_model/doc2vec
key_file           : keys/db_coords.yml
pickle_dir          : pickle/
text_pickle_file     : pickle/texts.p
bigrams_pickle_file     : pickle/bigrams.p
trigrams_pickle_file     : pickle/trigrams.p
phrases_model_dir_base    : models/phrases/phrases__
phrases_model_dir_link     : models/phrases/phrases_model
xgboost_model_file        : models/xgboost/xgboost_model
xgboost_classifier_file        : models/xgboost/xgboost_classifier
version                   : 1
threshold         : 0.92


