root_dir  : /media/diego/QData/techarticles_phrases/
list_name : /media/diego/QData/techarticles_phrases/lists/article_list.json
parsed_articles_dir : /media/diego/QData/techarticles_phrases/parsed_articles/
lsi_models_dir_base : /media/diego/QData/techarticles_phrases/models/lsi/lsi_
lsi_models_dir_link : /media/diego/QData/techarticles_phrases/models/lsi/lsi_model
doc2vec_models_dir_base : /media/diego/QData/techarticles_phrases/models/doc2vec/doc2vec__
doc2vec_models_dir_link : /media/diego/QData/techarticles_phrases/models/doc2vec/doc2vec_model
doc2vec_models_file_link : /media/diego/QData/techarticles_phrases/models/doc2vec/doc2vec_model/doc2vec
raw_base_dir        : /media/diego/QData/techarticles_phrases/raw_articles/
parsed_base_dir     : /media/diego/QData/techarticles_phrases/parsed_articles/
search_results_dir  : /media/diego/QData/techarticles_phrases/search_results/
search_pattern      : /media/diego/QData/techarticles_phrases/search_results/*.json
link_file           : /media/diego/QData/techarticles_phrases/lists/article_list_5_10_2017.json
commands_dir        : /media/diego/QData/techarticles_phrases/commands/
commands_pattern    : /media/diego/QData/techarticles_phrases/commands/*.json
google_key_file     : /media/diego/QData/techarticles_phrases/keys/google_search.yml
key_file           : /media/diego/QData/techarticles_phrases/keys/db_coords.yml
pickle_dir          : /media/diego/QData/techarticles_phrases/pickle/
text_pickle_file     : /media/diego/QData/techarticles_phrases/pickle/texts.p
bigrams_pickle_file     : /media/diego/QData/techarticles_phrases/pickle/bigrams.p
trigrams_pickle_file     : /media/diego/QData/techarticles_phrases/pickle/trigrams.p

phrases_model_dir_base    : /media/diego/QData/techarticles_phrases/models/phrases/phrases__
phrases_model_dir_link     : /media/diego/QData/techarticles_phrases/models/phrases/phrases_model

