DROP PROCEDURE delete_article;
CREATE PROCEDURE delete_article(IN id INT)
  BEGIN
    DELETE FROM SAME_STORY WHERE (SST_AIN_ID_1 = id OR SST_AIN_ID_2 = id);
    DELETE FROM SAME_STORY_USER WHERE (SSU_AIN_ID_1 = id OR SSU_AIN_ID_2 = id);
    DELETE FROM ARTICLE_AUTHORS WHERE AAU_AIN_ID = id;
    DELETE FROM ARTICLE_TAGS WHERE ATA_AIN_ID = id;
    DELETE FROM ARTICLE_TEXT WHERE ATX_AIN_ID = id;
    DELETE FROM ARTICLE_INFO WHERE AIN_ID = id ;
  COMMIT;
END;
