DELETE FROM SAME_STORY;
DELETE FROM SAME_STORY_USER;
DELETE FROM SAME_STORY_JOBS;
DELETE FROM ARTICLE_TAGS;
DELETE FROM ARTICLE_AUTHORS;
DELETE FROM AUTHORS;
DELETE FROM TAGS;
DELETE FROM ARTICLE_TEXT;
DELETE FROM ARTICLE_INFO;
COMMIT;



