DELIMITER $$
DROP PROCEDURE IF EXISTS  detect_dup_txts $$
CREATE PROCEDURE `detect_dup_txts`()
BEGIN
DECLARE id   INT;
DECLARE exit_loop BOOLEAN;
DECLARE DUP_ATX_TXT_ID_CURSOR CURSOR FOR SELECT ATX_ID FROM ARTICLE_TEXT,
    (select ATX_TEXT AS ATTEXT, ATX_AIN_ID AS AAI,  COUNT(*) AS CNT, MAX(ATX_ID) AS MAXA_ID from ARTICLE_TEXT GROUP BY ATX_TEXT, ATX_AIN_ID HAVING CNT > 1 ORDER BY CNT DESC ) AIN_DUP
  WHERE ATTEXT = ATX_TEXT AND AAI = ATX_AIN_ID AND ATX_ID != MAXA_ID;
DECLARE CONTINUE HANDLER FOR NOT FOUND SET exit_loop = TRUE;
OPEN DUP_ATX_TXT_ID_CURSOR ;
  dup_aid_loop: LOOP
       FETCH  DUP_ATX_TXT_ID_CURSOR INTO id;
       INSERT INTO TODELETE_TXT (TOD_TXT_ID) VALUES(id);
       IF exit_loop THEN
           CLOSE DUP_ATX_TXT_ID_CURSOR;
           LEAVE dup_aid_loop;
       END IF;
  END LOOP dup_aid_loop;
END