SELECT COUNT(*) AS CNT, ATA_AIN_ID, ATA_TAG_ID FROM ARTICLE_INFO, ARTICLE_TAGS, TAGS WHERE ATA_AIN_ID = AIN_ID AND TAG_ID = ARTICLE_TAGS.ATA_TAG_ID GROUP BY ATA_AIN_ID, ATA_TAG_ID ORDER BY CNT DESC;
SELECT COUNT(*) AS CNT, AAU_AIN_ID, AAU_AUT_ID FROM ARTICLE_INFO, ARTICLE_AUTHORS, AUTHORS WHERE AAU_AIN_ID = AIN_ID AND AUT_ID = AAU_AUT_ID GROUP BY  AAU_AIN_ID, AAU_AUT_ID  ORDER BY CNT DESC;
SELECT AIN_ID FROM ARTICLE_INFO WHERE NOT EXISTS (SELECT ATX_AIN_ID FROM ARTICLE_TEXT WHERE ATX_AIN_ID = AIN_ID);

