CREATE OR REPLACE VIEW TEST_SCORES AS
  SELECT
    `SCORES`.`SCO_AIN_ID_1`     AS `SCO_AIN_ID_1`,
    `SCORES`.`SCO_AIN_ID_2`     AS `SCO_AIN_ID_2`,
    `SCORES`.`SCO_T_TITLE`      AS `SCO_T_TITLE`,
    `SCORES`.`SCO_D_TITLE`      AS `SCO_D_TITLE`,
    `SCORES`.`SCO_T_TEXT`      AS `SCO_T_TEXT`,
    `SCORES`.`SCO_D_TEXT`      AS `SCO_D_TEXT`,
    `SCORES`.`SCO_T_SUMMARY`    AS `SCO_T_SUMMARY`,
    `SCORES`.`SCO_D_SUMMARY`    AS `SCO_D_SUMMARY`,
    `SCORES`.`SCO_T_SUMMARY_2`  AS `SCO_T_SUMMARY_2`,
    `SCORES`.`SCO_D_SUMMARY_2`  AS `SCO_D_SUMMARY_2`,
    `SCORES`.`SCO_CW_TITLE`     AS `SCO_CW_TITLE`,
    `SCORES`.`SCO_CW_SUMMARY`   AS `SCO_CW_SUMMARY`,
    `SCORES`.`SCO_CW_SUMMARY_2` AS `SCO_CW_SUMMARY_2`,
    `SCORES`.`SCO_CW_TEXT`      AS `SCO_CW_TEXT`,
    `SCORES`.`SCO_VERSION`      AS `SCO_VERSION`,
    `SCORES`.`SCO_DAYS`      AS `SCO_DAYS`


  FROM `SCORES`
    JOIN (SELECT
            `SAME_STORY`.`SST_AIN_ID_1` AS `SST_AIN_ID_1`,
            `SAME_STORY`.`SST_AIN_ID_2` AS `SST_AIN_ID_2`
          FROM `SAME_STORY`
          GROUP BY `SAME_STORY`.`SST_AIN_ID_1`,
            `SAME_STORY`.`SST_AIN_ID_2`) `SAME_STORY_GRP`
  WHERE ((`SCORES`.`SCO_AIN_ID_1` = `SAME_STORY_GRP`.`SST_AIN_ID_1`) AND
         (`SCORES`.`SCO_AIN_ID_2` = `SAME_STORY_GRP`.`SST_AIN_ID_2`));
