CREATE OR REPLACE VIEW TRAIN_SCORES AS
  SELECT
    `SCORES`.`SCO_AIN_ID_1`     AS `SCO_AIN_ID_1`,
    `SCORES`.`SCO_AIN_ID_2`     AS `SCO_AIN_ID_2`,
    `SCORES`.`SCO_T_TITLE`      AS `SCO_T_TITLE`,
    `SCORES`.`SCO_D_TITLE`      AS `SCO_D_TITLE`,
    `SCORES`.`SCO_T_TEXT`      AS `SCO_T_TEXT`,
    `SCORES`.`SCO_D_TEXT`      AS `SCO_D_TEXT`,
    `SCORES`.`SCO_T_SUMMARY`    AS `SCO_T_SUMMARY`,
    `SCORES`.`SCO_D_SUMMARY`    AS `SCO_D_SUMMARY`,
    `SCORES`.`SCO_T_SUMMARY_2`  AS `SCO_T_SUMMARY_2`,
    `SCORES`.`SCO_D_SUMMARY_2`  AS `SCO_D_SUMMARY_2`,
    `SCORES`.`SCO_CW_TITLE`     AS `SCO_CW_TITLE`,
    `SCORES`.`SCO_CW_SUMMARY`   AS `SCO_CW_SUMMARY`,
    `SCORES`.`SCO_CW_SUMMARY_2` AS `SCO_CW_SUMMARY_2`,
    `SCORES`.`SCO_CW_TEXT`      AS `SCO_CW_TEXT`,
    `SCORES`.`SCO_VERSION`      AS `SCO_VERSION`,
    `SCORES`.`SCO_DAYS`      AS `SCO_DAYS`,
    `SAME_STORY_USER_GRP`.`SSU_SCORE`      AS `SCO_USER`


  FROM `SCORES`
    JOIN (SELECT
            `SAME_STORY_USER`.`SSU_AIN_ID_1` AS `SSU_AIN_ID_1`,
            `SAME_STORY_USER`.`SSU_AIN_ID_2` AS `SSU_AIN_ID_2`,
            AVG(`SAME_STORY_USER`.`SSU_SIMILARITY`) AS SSU_SCORE
          FROM `SAME_STORY_USER`
          GROUP BY `SAME_STORY_USER`.`SSU_AIN_ID_1`,
            `SAME_STORY_USER`.`SSU_AIN_ID_2`) `SAME_STORY_USER_GRP`
  WHERE ((`SCORES`.`SCO_AIN_ID_1` = `SAME_STORY_USER_GRP`.`SSU_AIN_ID_1`) AND
         (`SCORES`.`SCO_AIN_ID_2` = `SAME_STORY_USER_GRP`.`SSU_AIN_ID_2`));
