---
### provision AWS EC2 instance
- hosts: aws
  remote_user: ec2_user
  become_method: sudo
  gather_facts: yes
  connection: ssh

  tasks:
  - name: Excecute a shell command for listing the directory
    shell: ls -al ~
    register: result

  - name: Display the results in Json format
    debug: var=result
  - name: Install packages
    become: true
    apt:
      name: wget curl gcc libmysqlclient-dev mysql-client mysql-server
    with_items: "{{ ec2.instances }}"



  - name: Install anaconda
    shell:
      wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
      bash Miniconda3-latest-Linux-x86_64.sh -b
    with_items: "{{ ec2.instances }}"


  - name: install project
    shell:
      mkdir ~/projects
      cd ~/projects
    with_items: "{{ ec2.instances }}"


