STATE_RES_NAME: "Test_Nano"
ec2_region: "eu-central-1"
ec2_instance_type: "t2.nano"
ec2_image: "ami-7c412f13"
ec2_keypair: "Diego 3"
ec2_volume_size: 12
ec2_count: 1
ec2_security_group_id: "sg-5970c933"
ec2_subnet_id: "subnet-8cc6f7f6"
ec2_tag_Type: "Test_Tag_Nano_1"
ec2_tag_Role: "Test_Tag_Role_1"
ec2_instances: "i-08e6d7ad2e4fc2ed2"