from technews_nlp_aggregator.model_usage.clf_facade import ClfFacade
from technews_nlp_aggregator.model_usage.doc2vec_facade import Doc2VecFacade
from technews_nlp_aggregator.model_usage.tfidf_facade import TfidfFacade
